test:
  stage: test
  script:
  - bundle install
  - rails db:migrate
  - rails test

deploy:
  stage: deploy
  script:
  - puma-stop
  - bundle install
  - rails db:migrate
  - nuhup rails server -d -b 0.0.0.0 -p 3000 &
  only:
  - master